# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raging Scholar
email: hailang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    uprintf("There is no place like ::1\n");
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ragingscholar.github.io" # the base hostname & protocol for your site
twitter_username: ragingscholar
github_username:  ragingscholar

# Build settings
markdown: kramdown
